<?php

/**
 * @file
 * Contains task_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function task_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the task_api module.
    case 'help.page.task_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows users to create and assign tasks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function task_api_theme() {
  return [
    'task_api' => [
      'render element' => 'children',
    ],
  ];
}
