task_api.task_config.*:
  type: config_entity
  label: 'Task Configuration config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
