task.task_closure_reason.*:
  type: config_entity
  label: 'Task Closure Reason config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    locked:
      type: boolean
      label: 'Locked from Edit/Delete'
    uuid:
      type: string
