task.task_type.*:
  type: config_entity
  label: 'Task type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    allowed_statuses:
      type: sequence
      label: 'Allowed Statuses'
      sequence:
        type: string
        label: 'Status'
    uuid:
      type: string
